# -*- coding: utf-8 -*-
#
# java all documentation build configuration file, created by
# sphinx-quickstart on Thu Mar 22 11:16:23 2018.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys

PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, PROJECT_DIR)
sys.path.insert(0, os.path.join(PROJECT_DIR, 'libs'))
os.environ["PATH"] = "{0}:{1}".format(PROJECT_DIR, os.environ["PATH"])
# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.mathjax',
    'sphinx.ext.ifconfig',
    'sphinx.ext.viewcode',
    'sphinx.ext.githubpages',
    "sphinxcontrib.plantuml",
    "sphinx_needs",
    "sphinx_rtd_theme",
    'sphinx.ext.inheritance_diagram',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = ['.rst', '.md']

source_parsers = {
    '.md': 'recommonmark.parser.CommonMarkParser',
}

# The master toctree document.
master_doc = 'index'
import datetime

# General information about the project.
project = u't-reqs-needs'
copyright = u'{0}, Volker Kempert'.format(datetime.datetime.now().year)
author = u'Volker Kempert'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = u'0.0.1'
# The full version, including alpha/beta/rc tags.
release = u'0.0.1'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = True

# -- Needs config ----------------


needs_types = [
    dict(directive="need", title="User Need", prefix="UN_"),
    dict(directive="sysreq",  title="System Requirement", prefix="SYR_"),
    dict(directive="sysspec",  title="System Specification", prefix="SYS_"),

    dict(directive="swreq",   title="Software Requirement", prefix="SWR_"),
    dict(directive="swspec", title="Specification", prefix="SWS_"),

    dict(directive="test", title="SoftwareTest Case", prefix="SWT_"),

    dict(directive="elreq",   title="Electronics Requirement", prefix="ELR_"),


    dict(directive="con",  title="Constraint", prefix="CON_"),
    dict(directive="risk", title="Risk", prefix="RSK_"),
    dict(directive="hazard", title="Hazard", prefix="HAZ_"),
]

needs_links = {
    "derives": {
        "incoming": "derived from",
        "outgoing": "derives to",
    },
    "implements": {
        "incoming": "implemented by",
        "outgoing": "implements",
    },
    "verifies": {
        "incoming": "verified by",
        "outgoing": "verifies",
    },
    "constrains": {
        "incoming": "constrained by",
        "outgoing": "constrains",
    },
    "mitigates": {
        "incoming": "mitigated by",
        "outgoing": "mitigates",
    },
    "causes": {
        "incoming": "caused by",
        "outgoing": "causes",
    },
}


needs_fields = {
    "severity": {
        "description": "Applies to risks",
        "schema": {
            "type": "string",
        },
        "nullable": True,
    },
    "probability": {
        "description": "Applies to hazards",
        "schema": {
            "type": "string",
        },
        "nullable": True,
    },
    "origin": {
        "description": "Link back to user needs, or hazards for risk controls",
        "schema": {
            "type": "string",
        },
        "nullable": True,
    },
    "subsystem": {
        "description": "If a distribution to different subsystems is needed",
        "schema": {
            "type": "string",
        },
        "nullable": True,
    },
}

needs_constraints = {

    "severity_enum": {
        "check": "severity" in [ "low", "medium", "high", "critical" ],
        "error_message": "severity must be one of: low, medium, high, critical",
    },
    "probability_enum": {
        "check": "probability" in [ "very_low", "low", "medium", "high", "very_high" ],
        "error_message": "probability must be one of: very_low, low, medium, high, very_high ",
    },
    "origin_enum": {
        "check": "origin" in [ "user_need", "risk_control" ],
        "error_message": "origin must be one of: user_need, risk_control",
    },

    "swreq_must_have_test": {
        "check": "type == 'swreq' and not links_back",
        "severity": "HIGH",
        "error_message": "Software requirement has no test"
    },

    "risk_must_have_control": {
        "check": "type == 'risk' and not links_back",
        "severity": "HIGH",
        "error_message": "Risk has no mitigation requirement"
    },
    "risk_control_must_be_tested": {
        "check": "origin == 'risk_control' and not links_back",
        "severity": "HIGH",
        "error_message": "Risk control not verified"
    }
}

# -- Options for HTML output ----------------------------------------------

html_theme = 'sphinx_rtd_theme'
html_theme_options = {
    'logo_only': False,
    'prev_next_buttons_location': 'bottom',
    'style_external_links': False,
    'vcs_pageview_mode': '',
    'style_nav_header_background': 'white',
    'flyout_display': 'hidden',
    'version_selector': True,
    'language_selector': False,
    # Toc options
    'collapse_navigation': True,
    'sticky_navigation': True,
    'navigation_depth': 3,
    'includehidden': True,
    'titles_only': False
}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['_static']




# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'treqdoc'

# -- Options for LaTeX output ---------------------------------------------



# --  latex config ----------------


latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    'papersize': 'a4paper',

    # The font size ('10pt', '11pt' or '12pt').
    # 'pointsize': '12pt',
    'pointsize': '10pt',
    # 'classoptions': ',english',
    'inputenc': '',
    'utf8extra': '',

    # Additional stuff for the LaTeX preamble.

}

# --  planuml config ----------------
plantuml_theme = "azusa-color"
plantuml_jar_path = os.path.join(PROJECT_DIR, "plantuml.jar")
# plantuml = "java -jar " + "-Iplantuml_themes/{1}.pu {0}".format(plantuml_jar_path, plantuml_theme)
plantuml_output_format = "svg"
plantuml_latex_output_format = "eps"



